# Generated by Django 6.0.5 on 2026-06-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_streak_userprofile_current_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='highest_rating',
            field=models.IntegerField(default=1000),
        ),
    ]
