# Generated by Django 6.0.5 on 2026-06-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_remove_quizattempt_topic_quizattempt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
