# Generated by Django 6.0.5 on 2026-06-14 08:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_achievement_userachievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailychallenge',
            name='question',
        ),

        migrations.AlterModelOptions(
            name='userdailychallenge',
            options={'ordering': ['-date']},
        ),

        migrations.AlterUniqueTogether(
            name='userdailychallenge',
            unique_together=set(),
        ),

        migrations.AddField(
            model_name='userdailychallenge',
            name='date',
            field=models.DateField(
                default=datetime.date(2026, 6, 14)
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='userdailychallenge',
            name='earned_points',
            field=models.IntegerField(default=0),
        ),

        migrations.AddField(
            model_name='userdailychallenge',
            name='points',
            field=models.IntegerField(default=10),
        ),

        migrations.AddField(
            model_name='userdailychallenge',
            name='question',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_daily_challenges',
                to='quizzes.question',
            ),
        ),

        migrations.AlterField(
            model_name='userdailychallenge',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='daily_challenges',
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        migrations.AddConstraint(
            model_name='userdailychallenge',
            constraint=models.UniqueConstraint(
                fields=('user', 'date'),
                name='unique_user_daily_challenge',
            ),
        ),

        migrations.RemoveField(
            model_name='userdailychallenge',
            name='challenge',
        ),

        migrations.DeleteModel(
            name='DailyChallenge',
        ),
    ]