# Generated by Django 6.0.5 on 2026-06-14 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_remove_dailychallenge_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailychallenge',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_daily_challenges', to='quizzes.question'),
        ),
    ]
