services:
  - type: static
    name: engineering-quiz-arena-1
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist

    routes:
      - type: rewrite
        source: /*
        destination: /index.html